[general]
import = [
    "~/dotfiles/.config/alacritty/themes/gruvbox_material.toml"
]

[font]
size = 12

[font.normal]
family = "Fira Code"

[[keyboard.bindings]]
action = "None"
key = "N"
mods = "Command"

[window.padding]
y = 5
x = 5

[window]
opacity = 0.9
