# theme = "catppuccin_macchiato"
# theme = "ayu_evolve"
theme = "gruvbox"

[editor]
lsp.display-inlay-hints = true
bufferline = "multiple"
cursorline = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

